#
# Use Flight MFA authentication for specified client sources
#
#
# A user coming in from the "Match" source must have:
# - A password set
# - At least one SSH public key setup in ~/.ssh/authorized_keys
#
#
# Client connections coming in from the "Match" source will behave as follows:
# - If the user has no MFA setup they can login with their public key and password
# - If the user has MFA setup they must use public key, password and TOTP
#
#
# Besides this file, other configuration that needs to be in place:
# - Flight User Suite installed
# - The Flight User Suite mfa tool enabled and configured
# - Package dependencies present (google-authenticator and qrencode)
# - A line matching the following in /etc/pam.d/sshd
#   auth required pam_google_authenticator.so secret=${HOME}/.config/flight/mfa.dat [authtok_prompt=Enter your TOTP: ] nullok

# WARNING: 'UsePAM no' is not supported by Flight MFA.
UsePAM yes

#
# Set this to the client source subnet range to enforce MFA for.
# - Exclude a trusted IP or subnet with ",!10.151.0.234/32" at the end
#
Match Address 10.151.0.0/24
  # Don't allow root user connections
  PermitRootLogin no

  # Allow password authentication for this source
  # (Only needed when allowing publickey,password AuthenticationMethods)
  PasswordAuthentication yes

  # Required for MFA OTP prompting
  KbdInteractiveAuthentication yes

  # Optionally allow X11 forwarding.
  X11Forwarding yes

  # Optionally, allow some environemnt variables to be passed in from the client.
  #AcceptEnv LANG LC_CTYPE LC_NUMERIC LC_TIME LC_COLLATE LC_MONETARY LC_MESSAGES
  #AcceptEnv LC_PAPER LC_NAME LC_ADDRESS LC_TELEPHONE LC_MEASUREMENT
  #AcceptEnv LC_IDENTIFICATION LC_ALL LANGUAGE
  #AcceptEnv XMODIFIERS

  # Valid authorisation combos are publickey+MFA(pass+OTP) or publickey+pass(if MFA config not present)
  AuthenticationMethods publickey,keyboard-interactive publickey,password
