#!/bin/bash
#==============================================================================
# Copyright (C) 2026 Stephen F Norledge & Alces Software Ltd & Concertim Ltd
#
# This file is part of Flight User Suite.
#
# This program and the accompanying materials are made available under
# the terms of the Eclipse Public License 2.0 which is available at
# <https://www.eclipse.org/legal/epl-2.0>, or alternative license
# terms made available by Alces Software Ltd - please direct inquiries
# about licensing to licensing@alces-software.com.
#
# Flight User Suite is distributed in the hope that it will be useful, but
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, EITHER EXPRESS OR
# IMPLIED INCLUDING, WITHOUT LIMITATION, ANY WARRANTIES OR CONDITIONS
# OF TITLE, NON-INFRINGEMENT, MERCHANTABILITY OR FITNESS FOR A
# PARTICULAR PURPOSE. See the Eclipse Public License 2.0 for more
# details.
#
# You should have received a copy of the Eclipse Public License 2.0
# along with Flight User Suite. If not, see:
#
#  https://opensource.org/licenses/EPL-2.0
#
# For more information on Flight User Suite, please visit:
# https://github.com/alces-flight/flight-user-suite
#==============================================================================
set -euo pipefail

main() {
    if [ $(id -u) = 0 ]; then
        # Don't create symlinks for root
        exit 0
    fi
    echo "Creating symlinks"
    local target link_name config
    config="$( cat "${FLIGHT_ROOT}"/etc/user-symlinks.config | sed -e '/^#/d' -e '/^\s*$/d' )"
    IFS=$'\n' read -a links <<< "${config}"
    for link in "${links[@]}"; do
        IFS='=' read -a link_desc <<< "${link}"
        link_name="$(eval echo ${link_desc[0]})"
        target="$(eval echo ${link_desc[1]})"

        if [ -L "${link_name}" ] ; then
            echo "  ${link_name} : already exists"
            return 0
        fi
        ln -s "${target}" "${link_name}"
        echo "  ${link_name}->${target} : created"
    done
}

FLIGHT_ROOT=${FLIGHT_ROOT:-/opt/flight}

if [ -f "${FLIGHT_ROOT}"/etc/user-symlinks.config ]; then
    main
fi
