#!/bin/bash
set -euo pipefail

main() {
    parse_arguments "$@"
}

usage() {
	cat <<EOF
Usage: $(basename $0) [--help] [list]

View user guides for your HPC environment.

    --help		Show this help message
EOF
}

parse_arguments() {
    while [[ $# > 0 ]] ; do
        key="$1"

        case $key in
            --help)
                usage
                exit 0
                ;;

            --*)
                echo "$(basename $0): unrecognized option ${key}"
                usage
                exit 1
                ;;

            list*)
                ls -1 "${FLIGHT_ROOT:-/opt/flight}"/usr/share/doc/howtos-enabled/
                exit 0
                ;;

            *)
                echo "$(basename $0): unrecognized command ${key}"
                exit 2
                shift
                ;;
        esac
    done
}

main "$@"
