#!/usr/bin/env python3
#==============================================================================
# Copyright (C) 2019-present Concertim Ltd.
#
# This file is part of Flight User Suite.
#
# This program and the accompanying materials are made available under
# the terms of the Eclipse Public License 2.0 which is available at
# <https://www.eclipse.org/legal/epl-2.0>, or alternative license
# terms made available by Alces Flight Ltd - please direct inquiries
# about licensing to licensing@concertim.com.
#
# Flight Runway is distributed in the hope that it will be useful, but
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, EITHER EXPRESS OR
# IMPLIED INCLUDING, WITHOUT LIMITATION, ANY WARRANTIES OR CONDITIONS
# OF TITLE, NON-INFRINGEMENT, MERCHANTABILITY OR FITNESS FOR A
# PARTICULAR PURPOSE. See the Eclipse Public License 2.0 for more
# details.
#
# You should have received a copy of the Eclipse Public License 2.0
# along with Flight Runway. If not, see:
#
#  https://opensource.org/licenses/EPL-2.0
#
# For more information on Flight User Suite, please visit:
# https://github.com/alces-flight/flight-user-suite
#==============================================================================
import re
import sys

def main():
    if len(sys.argv) not in [3, 4]:
        print("Usage augment-bash-prompt <PS1> <injection> [<colour>]")
        sys.exit(1)

    ps1 = sys.argv[1]
    injection = sys.argv[2]
    if len(sys.argv) > 3:
        colour = sys.argv[3]
        injection = f"\\[\\e[{colour}m\\]{injection}\\[\\e[0m\\]"

    inside_escape_sequence = False
    injected = False

    # Split into PS1 escape segments and non-escape text
    parts = re.split(r'(\\\[)(.*?)(\\\])', ps1)
    mapped = []

    for x in parts:
        if x == r'\[':
            inside_escape_sequence = True
        elif x == r'\]':
            inside_escape_sequence = False
        elif not inside_escape_sequence and not injected:
            if r'\h' in x:
                x = x.replace(r'\h', f"\\h {injection}", 1)
                injected = True
            elif r'\W' in x:
                x = x.replace(r'\W', f"{injection} \\W", 1)
                injected = True
            elif r'\w' in x:
                x = x.replace(r'\w', f"{injection} \\w", 1)
                injected = True
            elif r'\$' in x:
                x = x.replace(r'\$', f"{injection} \\$", 1)
                injected = True
        mapped.append(x)

    print("".join(mapped))

if __name__ == "__main__":
  main()
