#!/bin/bash
#==============================================================================
# Copyright (C) 2026 Stephen F Norledge & Alces Software Ltd & Concertim Ltd
#
# This file is part of Flight User Suite.
#
# This program and the accompanying materials are made available under
# the terms of the Eclipse Public License 2.0 which is available at
# <https://www.eclipse.org/legal/epl-2.0>, or alternative license
# terms made available by Alces Software Ltd - please direct inquiries
# about licensing to licensing@alces-software.com.
#
# Flight User Suite is distributed in the hope that it will be useful, but
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, EITHER EXPRESS OR
# IMPLIED INCLUDING, WITHOUT LIMITATION, ANY WARRANTIES OR CONDITIONS
# OF TITLE, NON-INFRINGEMENT, MERCHANTABILITY OR FITNESS FOR A
# PARTICULAR PURPOSE. See the Eclipse Public License 2.0 for more
# details.
#
# You should have received a copy of the Eclipse Public License 2.0
# along with Flight User Suite. If not, see:
#
#  https://opensource.org/licenses/EPL-2.0
#
# For more information on Flight User Suite, please visit:
# https://github.com/alces-flight/flight-user-suite
#==============================================================================
process_wait_for_pid() {
    local pid
    pid=$1
    while [ -d /proc/$pid ]; do
        sleep 5 &
        # Wait for the backgrounded sleep to complete. Running the sleep in the
        # background, allows this process to be responsive to any signals it
        # receives.
        wait $!
    done
}

process_wait_for_pid $SESSION_VNC_PID

for a in $SESSION_PIDS; do
  kill $a
done

if [ -z "$FLIGHT_DESKTOP_DEBUG" ]; then
  rm -rf $SESSION_DIR
fi
