#!/bin/bash
#==============================================================================
# Copyright (C) 2026 Stephen F Norledge & Alces Software Ltd & Concertim Ltd
#
# This file is part of Flight User Suite.
#
# This program and the accompanying materials are made available under
# the terms of the Eclipse Public License 2.0 which is available at
# <https://www.eclipse.org/legal/epl-2.0>, or alternative license
# terms made available by Alces Software Ltd - please direct inquiries
# about licensing to licensing@alces-software.com.
#
# Flight User Suite is distributed in the hope that it will be useful, but
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, EITHER EXPRESS OR
# IMPLIED INCLUDING, WITHOUT LIMITATION, ANY WARRANTIES OR CONDITIONS
# OF TITLE, NON-INFRINGEMENT, MERCHANTABILITY OR FITNESS FOR A
# PARTICULAR PURPOSE. See the Eclipse Public License 2.0 for more
# details.
#
# You should have received a copy of the Eclipse Public License 2.0
# along with Flight User Suite. If not, see:
#
#  https://opensource.org/licenses/EPL-2.0
#
# For more information on Flight User Suite, please visit:
# https://github.com/alces-flight/flight-user-suite
#==============================================================================

if [ "${TERM}" == "" -o "${TERM}" == "dumb" ] ; then
  # We don't have a TERM set. Calls to 'tput' will fail, so let's abort early.
  exit 0
fi

IFS=: read -a xdg_config <<< "${XDG_CONFIG_HOME:-$HOME/.config}:${XDG_CONFIG_DIRS:-/etc/xdg}"
for a in "${xdg_config[@]}"; do
  if [ -e "${a}"/flight.config ]; then
    source "${a}"/flight.config
    break
  fi
done
FLIGHT_ROOT="${FLIGHT_ROOT:-/opt/flight}"

# Load in any settings set by 'flight config set'. Allowing per-user settings
# to override global settings.
if [ -e /etc/xdg/flight/settings.config ]; then
  source /etc/xdg/flight/settings.config
fi
if [ -e "${XDG_CONFIG_HOME:-$HOME/.config}"/flight/settings.config ]; then
  source "${XDG_CONFIG_HOME:-$HOME/.config}"/flight/settings.config
fi

if [ "${FLIGHT_AUTOSTART}" == "on" ] ; then
  # The banner shown when flight is started is welcome enough; no need to
  # also provide a separate welcome message.
  exit 0
fi

if [ -f "${FLIGHT_ROOT}"/etc/flight-starter.config ]; then
  . "${FLIGHT_ROOT}"/etc/flight-starter.config
fi

cluster="${FLIGHT_STARTER_CLUSTER_NAME:-your cluster}"
bold="$(tput bold)"
green="$(tput setaf 2)"
clr="$(tput sgr0)"
bgblack="$(tput setab 0)"
if [[ $TERM =~ "256color" ]]; then
  white="$(tput setaf 7)"
  bgblue="$(tput setab 68)"
  blue="$(tput setaf 68)"
  grey="$(tput setaf 249)"
  bwhite="$(tput setaf 15)"
fi
if [ -f /etc/redhat-release ]; then
  release="$(cut -f1,2,4 -d' ' /etc/redhat-release)"
  reltext=", based on ${bold}${release}${clr}"
elif [ -f /etc/lsb-release ]; then
  . /etc/lsb-release
  release="${DISTRIB_DESCRIPTION:-${DISTRIB_ID} ${DISTRIB_RELEASE}}"
  reltext=", based on ${bold}${release}${clr}"
fi
cat <<EOF
${bgblack} ${blue}-[${clr}${bgblack} ${bwhite}Flight${clr}${bgblack} ${blue}]- ${clr}
Welcome to ${bold}${bgblack}${green}${cluster}${clr}${reltext}.

EOF
  cat <<EOF
This cluster provides ${FLIGHT_STARTER_DESC}.

${bold}${white}'${bgblue}flight-start${clr}${bold}${white}'${clr} - activate ${FLIGHT_STARTER_PRODUCT} now

EOF
