on:
  push:
    branches: [main]
    tags: ["*"]
    paths-ignore: ['docs/**']
  pull_request:
    branches: [main]
    paths-ignore: ['docs/**']

permissions:
  contents: write

name: Build and test
jobs:
  test:
    name: Check Go deps and run Go tests
    runs-on: ${{ matrix.os }}
    timeout-minutes: 5

    strategy:
      fail-fast: true
      matrix:
        go: ['1.26.x']
        os: [ubuntu-latest]
        subdir: ["flight-core", "flight-desktop", "flight-howto", "flight-web-suite"]

    steps:
      - name: Check out code
        uses: actions/checkout@v6

      - name: Install Go
        uses: actions/setup-go@v6
        with:
          go-version: ${{ matrix.go }}
          check-latest: true

      - name: Go Tidy
        run: go mod tidy && git diff --exit-code
        working-directory: ${{ matrix.subdir }}

      - name: Go Mod
        run: go mod download
        working-directory: ${{ matrix.subdir }}

      - name: Go Mod Verify
        run: go mod verify
        working-directory: ${{ matrix.subdir }}

      - name: Go test
        run: go test -v -count=1 -race -shuffle=on ./...
        working-directory: ${{ matrix.subdir }}

  build:
    name: Build
    needs: test
    runs-on: ${{ matrix.os }}
    timeout-minutes: 5

    strategy:
      fail-fast: true
      matrix:
        go: ['1.26.x']
        os: [ubuntu-latest]
        # os: [ubuntu-latest, ubuntu-latest-arm]

    steps:
      - name: Check out code
        uses: actions/checkout@v6

      - name: Install Go
        uses: actions/setup-go@v6
        with:
          go-version: ${{ matrix.go }}
          check-latest: true

      - name: Build
        run: make

      - name: Publish build tarball
        uses: actions/upload-artifact@v7
        with:
          path: flight-user-suite*.tar.gz
          archive: false

      - name: Release
        uses: softprops/action-gh-release@v3
        if: ${{ github.ref_type == 'tag' }}
        with:
          files: |
            flight-user-suite*.tar.gz
          draft: true
          prerelease: true
          generate_release_notes: true
